# Generated by Django 2.0.6 on 2018-06-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
