# Generated by Django 2.0.6 on 2018-06-10 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_photo_liked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=10000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.User')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Photo')),
            ],
        ),
    ]
