# Generated by Django 2.0.6 on 2018-06-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_url',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.FileField(upload_to=''),
        ),
    ]
